name: kratos
services:
  kratos:
    command:
      - serve
      - -c
      - /etc/config/kratos/kratos.yml
      - --dev
      - --watch-courier
    depends_on:
      kratos-migrate:
        condition: service_started
        required: true
    environment:
      DSN: sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      LOG_LEVEL: trace
    image: oryd/kratos:v1.3.1
    networks:
      intranet: null
    ports:
      - mode: ingress
        target: 4433
        published: "4433"
        protocol: tcp
      - mode: ingress
        target: 4434
        published: "4434"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
  kratos-migrate:
    command:
      - -c
      - /etc/config/kratos/kratos.yml
      - migrate
      - sql
      - -e
      - --yes
    environment:
      DSN: sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    image: oryd/kratos:v1.3.1
    networks:
      intranet: null
    restart: on-failure
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
  kratos-selfservice-ui-node:
    environment:
      COOKIE_SECRET: changeme
      CSRF_COOKIE_NAME: ory_csrf_ui
      CSRF_COOKIE_SECRET: changeme
      KRATOS_BROWSER_URL: http://127.0.0.1:4433/
      KRATOS_PUBLIC_URL: http://kratos:4433/
      PORT: "4455"
      SECURITY_MODE: ""
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    networks:
      intranet: null
    ports:
      - mode: ingress
        target: 4455
        published: "4455"
        protocol: tcp
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      intranet: null
    ports:
      - mode: ingress
        target: 4436
        published: "4436"
        protocol: tcp
      - mode: ingress
        target: 4437
        published: "4437"
        protocol: tcp
networks:
  intranet:
    name: kratos_intranet
volumes:
  kratos-sqlite:
    name: kratos_kratos-sqlite
