name: kratos
services:
  kratos:
    image: oryd/kratos:v1.3.1
    command:
      - serve
      - -c
      - /etc/config/kratos/kratos.yml
      - --dev
      - --watch-courier
    depends_on:
      kratos-migrate:
        condition: service_started
    environment:
      DSN: sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      LOG_LEVEL: trace
    networks:
      - intranet
    ports:
      - "4433:4433"
      - "4434:4434"
    restart: unless-stopped
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ./config:/etc/config/kratos
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    command:
      - -c
      - /etc/config/kratos/kratos.yml
      - migrate
      - sql
      - -e
      - --yes
    environment:
      DSN: sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    networks:
      - intranet
    restart: on-failure
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ./config:/etc/config/kratos
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    environment:
      COOKIE_SECRET: changeme
      CSRF_COOKIE_NAME: ory_csrf_ui
      CSRF_COOKIE_SECRET: changeme
      KRATOS_BROWSER_URL: http://127.0.0.1:4433/
      KRATOS_PUBLIC_URL: http://kratos:4433/
      PORT: "4455"
      SECURITY_MODE: ""
    networks:
      - intranet
    ports:
      - "4455:4455"
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - intranet
    ports:
      - "4436:4436"
      - "4437:4437"
networks:
  intranet:
    name: kratos_intranet
volumes:
  kratos-sqlite:
    name: kratos_kratos-sqlite
