.PHONY:clone
clone:
	rm -rf ./kratos-selfservice-ui-node
	git clone https://github.com/ory/kratos-selfservice-ui-node.git
	cd kratos-selfservice-ui-node && git checkout bed6795f78290c85970ddc8c8f7068e2a5f6e674

.PHONY:reset
reset: clone
