.PHONY:clone
clone:
	rm -rf ./kratos-selfservice-ui-react-nextjs
	git clone https://github.com/ory/kratos-selfservice-ui-react-nextjs.git
	cd kratos-selfservice-ui-react-nextjs && git checkout 15d1ee6efc22d50a63ef1cbb3e2d2a365a10eade

.PHONY:reset
reset: clone
